import * as luau from "LuauAST/bundle";

const COROUTINE_ID = luau.id("coroutine");
const MATH_ID = luau.id("math");
const STRING_ID = luau.id("string");
const TABLE_ID = luau.id("table");
const UTF8_ID = luau.id("utf8");

export const globals = {
	_G: luau.id("_G"),
	TS: luau.id("TS"),
	assert: luau.id("assert"),
	bit32: luau.id("bit32"),
	coroutine: {
		yield: luau.property(COROUTINE_ID, "yield"),
	},
	error: luau.id("error"),
	exports: luau.id("exports"),
	getmetatable: luau.id("getmetatable"),
	ipairs: luau.id("ipairs"),
	next: luau.id("next"),
	pairs: luau.id("pairs"),
	pcall: luau.id("pcall"),
	require: luau.id("require"),
	script: luau.id("script"),
	select: luau.id("select"),
	self: luau.id("self"),
	setmetatable: luau.id("setmetatable"),
	string: {
		byte: luau.property(STRING_ID, "byte"),
		find: luau.property(STRING_ID, "find"),
		format: luau.property(STRING_ID, "format"),
		gmatch: luau.property(STRING_ID, "gmatch"),
		gsub: luau.property(STRING_ID, "gsub"),
		lower: luau.property(STRING_ID, "lower"),
		match: luau.property(STRING_ID, "match"),
		rep: luau.property(STRING_ID, "rep"),
		reverse: luau.property(STRING_ID, "reverse"),
		split: luau.property(STRING_ID, "split"),
		sub: luau.property(STRING_ID, "sub"),
		upper: luau.property(STRING_ID, "upper"),
	},
	super: luau.id("super"),
	table: {
		clear: luau.property(TABLE_ID, "clear"),
		clone: luau.property(TABLE_ID, "clone"),
		concat: luau.property(TABLE_ID, "concat"),
		create: luau.property(TABLE_ID, "create"),
		find: luau.property(TABLE_ID, "find"),
		freeze: luau.property(TABLE_ID, "freeze"),
		insert: luau.property(TABLE_ID, "insert"),
		isfrozen: luau.property(TABLE_ID, "isfrozen"),
		maxn: luau.property(TABLE_ID, "maxn"),
		move: luau.property(TABLE_ID, "move"),
		pack: luau.property(TABLE_ID, "pack"),
		remove: luau.property(TABLE_ID, "remove"),
		sort: luau.property(TABLE_ID, "sort"),
		unpack: luau.property(TABLE_ID, "unpack"),
	},
	utf8: {
		charpattern: luau.property(UTF8_ID, "charpattern"),
		codes: luau.property(UTF8_ID, "codes"),
	},
	math: {
		abs: luau.property(MATH_ID, "abs"),
		acos: luau.property(MATH_ID, "acos"),
		asin: luau.property(MATH_ID, "asin"),
		atan: luau.property(MATH_ID, "atan"),
		atan2: luau.property(MATH_ID, "atan2"),
		ceil: luau.property(MATH_ID, "ceil"),
		clamp: luau.property(MATH_ID, "clamp"),
		cos: luau.property(MATH_ID, "cos"),
		cosh: luau.property(MATH_ID, "cosh"),
		deg: luau.property(MATH_ID, "deg"),
		exp: luau.property(MATH_ID, "exp"),
		floor: luau.property(MATH_ID, "floor"),
		fmod: luau.property(MATH_ID, "fmod"),
		frexp: luau.property(MATH_ID, "frexp"),
		huge: luau.property(MATH_ID, "huge"),
		ldexp: luau.property(MATH_ID, "ldexp"),
		log: luau.property(MATH_ID, "log"),
		log10: luau.property(MATH_ID, "log10"),
		max: luau.property(MATH_ID, "max"),
		min: luau.property(MATH_ID, "min"),
		modf: luau.property(MATH_ID, "modf"),
		noise: luau.property(MATH_ID, "noise"),
		pi: luau.property(MATH_ID, "pi"),
		pow: luau.property(MATH_ID, "pow"),
		rad: luau.property(MATH_ID, "rad"),
		random: luau.property(MATH_ID, "random"),
		randomseed: luau.property(MATH_ID, "randomseed"),
		round: luau.property(MATH_ID, "round"),
		sign: luau.property(MATH_ID, "sign"),
		sin: luau.property(MATH_ID, "sin"),
		sinh: luau.property(MATH_ID, "sinh"),
		sqrt: luau.property(MATH_ID, "sqrt"),
		tan: luau.property(MATH_ID, "tan"),
		tanh: luau.property(MATH_ID, "tanh"),
	},
	tostring: luau.id("tostring"),
	type: luau.id("type"),
	typeof: luau.id("typeof"),
	unpack: luau.id("unpack"),

	// roblox
	game: luau.id("game"),
};
